- package.json
- src/components/atoms/ModalButton.tsx
- src/components/modals/IsLoginModal.tsx
- src/layout/Header.tsx
- src/layout/MainLayout.tsx
- src/layout/Sidebar.tsx
- src/pages/Signup.tsx
- src/routes/index.tsx
- src/styles/index.css
비로그인 모달창 제작
---
---
- 준수님이 작성한 모달창을 참고하여, 비로그인 모달창을 구성했습니다.
- components/ModalButtons로 모달창의 버튼을 따로 만들어, 재사용성을 높였습니다.
---
-  tailwind css를 위한 클래스명 병합 패키지 twMerge 패키지 추가 설치.
---
https://github.com/user-attachments/assets/02e72634-deb0-4524-84c3-b796d99d3d88
---
- twMerge 패키지를 설치했으므로, 다음 작업 시에 npm install 부탁드립니다.
- 확인하시려면, 메인 페이지에서 '문제 게시판'을 누르면 확인하실 수 있습니다.
- 추가로, 이미지 경로가 잘못된 것을 수정했습니다.
> feat: 비로그인 모달창 제작 및 기능

- package.json
- src/components/ui/CustomConfirm.tsx
- src/main.tsx
- src/pages/Login.tsx
- src/pages/Signup.tsx
- src/utils/customAlert.ts
- src/utils/customConfirm.tsx
---
---
- 커스텀 alert을 추가했습니다. (utils/customAlert.ts)
- 로그인과 회원가입 시 커스텀 alert을 사용하도록 했습니다.
- 커스텀 confirm을 추가했습니다. (ui/CustomConfirm.tsx)
---
- react-toastify가 설치되었습니다.
---
- 로그인과 회원가입 시 커스텀 alert이 적용되었습니다.
<br><br>
- 커스텀 confirm 사용시 다음과 같이 보여집니다.
---
- `CustomConfirm`은 `confirm`을 사용하듯이 사용할 수 있습니다.
```
const confirmed = await CustomConfirm('보였으면 하는 메시지');
if (confirmed) {
확인시 실행할 코드
}
```
> feat: 커스텀 alert과 커스텀 confirm 추가

- src/components/edit/EditText.tsx
- src/components/edit/EditText.types.ts
- src/pages/question/QuestionEdit.tsx
- src/pages/question/QuestionList.tsx
질문게시판 글쓰기 DB저장
---
---
만약 내용에 이미지를 여러개 올린다면 이미지컬럼에 들어가는 첫번쨰로온 이미지(썸네일)
---
---
---
> feat: 질문 게시판 게시글 등록

- src/components/list/ProfileCommentCard.tsx
- src/components/list/ProfilePostCard.tsx
- src/layout/Header.tsx
- src/layout/Sidebar.tsx
- src/loader/profile.loader.ts
- src/pages/profile/Profile.tsx
- src/pages/profile/ProfileEdit.tsx
- src/routes/index.tsx
- src/styles/index.css
프로필 수정 기능  추가
---
---
cover_image, image, fullname, password(sns 로그인 제외) 수정 기능 추가
---
https://github.com/user-attachments/assets/bb24ec8d-bfc3-42ea-b0dc-f22c6c0b2cf7
---
- 프로필 화면에서 게시글보기, 댓글보기는 아직 개발이 안되어 있습니다. 참고부탁드립니다.
> Feature : 프로필 수정 기능

- src/api/postApi.ts
- src/api/userApi.ts
- src/components/detail/DetailText.tsx
- src/components/list/QuizListCard.tsx
- src/pages/HomePage.tsx
- src/pages/problem/quiz/JobDetailedPage.tsx
- src/pages/problem/quiz/QuizProblemList.tsx
- src/pages/question/QuestionList.tsx
- src/pages/solution/algorithm/AlgorithmSolutionList.tsx
- src/pages/solution/quiz/QuizSolutionList.tsx
- src/types/index.d.ts
- src/types/supabase.ts
푼 상태를 이제 계정 별로 상이하게 확인가능합니다.
---
---
- 수퍼베이스의 user 테이블의 solved 컬럼을 활용하여, 이제 푼 상태를 저장합니다.
- 푼 상태를 가져와서 푼 것들을 확인할 수 있습니다.
---
- 없음.
---
https://github.com/user-attachments/assets/6e80350f-f073-41c3-ac70-861d6933c762
---
- 이후로 풀이 작성 시, 풀이를 생성하는 로직으로 넘어가도록 구현하겠습니다.
> feat: 푼 상태를 계정 당 갱신으로 업데이트

- src/components/edit/CreateQuizSolution.tsx
- src/components/edit/EditText.types.ts
- src/components/list/QuizListCard.tsx
- src/components/list/QuizSolveListCard.tsx
- src/components/ui/Loading.tsx
- src/pages/problem/quiz/JobDetailedPage.tsx
- src/pages/question/QuestionEdit.tsx
- src/pages/solution/algorithm/AlgorithmSolutionEdit.tsx
- src/pages/solution/quiz/QuizSolutionDetail.tsx
- src/pages/solution/quiz/QuizSolutionEdit.tsx
- src/pages/solution/quiz/QuizSolutionList.tsx
- src/routes/index.tsx
개발직군 문제 풀이 생성이 가능하고 상세도 확인가능합니다.
---
---
- 원하는 문제의 풀이 작성을 누르면, 풀이가 작성되는 페이지로 넘어옵니다.
- 넘어온 페이지에서는 문제를 확인할 수 있고, 글을 바로 작성할 수 있습니다.
- 태그가 최대 5개까지만 생성하도록 로직 변경했습니다.
- 풀이 상세 페이지에서는 풀었던 문제를 확인 가능하고, 해당 문제로 바로가는 버튼도 추가했습니다.
---
- 없음.
---
https://github.com/user-attachments/assets/d0b159c3-1adf-45ea-877f-7c57789210f2
---
- 풀이가 보여지는 UI가 너무 가득차다고 생각해서, 수정이 좀 필요할 수 있겠습니다.
> Feat: 개발직군문제 풀이 게시글 생성 + 상세

- src/components/edit/EditText.tsx
- src/components/edit/EditText.types.ts
- src/pages/solution/algorithm/AlgorithmSolutionEdit.tsx
- src/styles/index.css
---
---
- 문제 내용 렌더링 디자인이 변경되었습니다.
- 문제 내용 렌더링 시 로딩 애니메이션이 추가되었습니다.
- 문제 풀이 게시글 작성과 게시글 등록이 가능합니다.
---
---
- 문제 내용 렌더링 디자인 변경
<br><br>
- 문제 풀이 게시글 작성 및 등록
---
> feat: 문제 풀이 게시글 작성 및 문제 내용 에디터 제거

- src/api/postApi.ts
- src/components/detail/DetailText.tsx
- src/components/list/ListCard.tsx
리스트 좋아요기능
---
---
---
---
32523 게시물 좋아요 2개
리스트에서 좋아요 버튼을 눌러서 좋아요 취소 
상세, 검색결과
상세에서 좋아요 버튼을 눌러서 좋아요 활성화 
리스트, 검색결과
---
> feat: 리스트 좋아요기능추가, 상세 좋아요 소스수정

- src/layout/MainLayout.tsx
- src/pages/HomePage.tsx
- src/styles/index.css
메인페이지 퍼블리싱 완료 했습니다.
헤더 스크롤 해도 상단에 Fix 되도록 수정했습니다.
---
---
- 메인페이지 퍼블리싱 완료 했습니다.
- 헤더 스크롤 해도 상단에 Fix 되도록 수정했습니다.
---
---
-  너무 단순해 보여서 각 컨텐츠 제목 앞에 아이콘을 넣어 봤는데 괜찮은지 봐주세요! 이상하면 빼겠습니다!
> Feature/main UI : 메인페이지 퍼블리싱

- src/api/searchApi.ts
- src/components/atoms/Navigation.tsx
- src/components/modals/DropdownMenu.tsx
- src/components/ui/Nopost.tsx
- src/pages/HomePage.tsx
- src/pages/problem/quiz/QuizProblemList.tsx
- src/pages/question/QuestionList.tsx
- src/pages/solution/quiz/QuizSolutionDetail.tsx
- src/pages/solution/quiz/QuizSolutionEdit.tsx
- src/types/supabase.ts
개발직군 문제를 위한 풀이를 생성 시, problem_id에 저장
---
---
- 없음.
---
- 없음.
---
- 없음.
---
- 없음.
> zap: 개발직군 문제 로직 가져오기 수정

- src/components/edit/EditText.tsx
- src/types/supabase.ts
---
---
- 템플릿 불러오기 및 저장 기능이 추가되었습니다.
- 저장된 템플릿이 없을 때는 불러오기 버튼을 클릭해도 에디터의 값이 변하지 않습니다.
---
---
- 템플릿 불러오기
<br><br>
- 템플릿 저장
---
> feat: 템플릿 불러오기 및 저장 기능 추가

- src/api/postApi.ts
- src/api/searchApi.ts
- src/components/search/SearchBox.tsx
- src/pages/problem/algorithm/AlgorithmProblemList.tsx
- src/pages/problem/quiz/QuizProblemList.tsx
- src/pages/question/QuestionList.tsx
- src/pages/solution/algorithm/AlgorithmSolutionList.tsx
- src/pages/solution/quiz/QuizSolutionList.tsx
각 채널에서 게시글의 제목과 내용을 검색할 수 있습니다. (알고리즘 문제 채널 제외)
---
---
- 채널 별 게시글 제목과 내용 검색 기능 추가.
---
- 없음.
---
https://github.com/user-attachments/assets/aef6b33c-7ca6-4cb0-a7cf-07842807899d
---
- 마크다운 내용이 검색되지 않게 필터링하고, 검색됩니다.
- 이후, 먼저 채널별 수정과 삭제 기능 연결 예정입니다
> Feat: 게시글 검색 기능

- src/components/detail/DetailText.tsx
- src/components/edit/CreateQuiz.tsx
- src/components/edit/CreateQuizSolution.tsx
- src/components/edit/EditText.types.ts
- src/pages/problem/quiz/JobDetailedPage.tsx
- src/pages/problem/quiz/QuizCreateEdit.tsx
- src/pages/problem/quiz/QuizProblemList.tsx
- src/pages/solution/algorithm/AlgorithmSolutionEdit.tsx
- src/pages/solution/algorithm/AlgorithmSolutionList.tsx
- src/pages/solution/quiz/QuizSolutionEdit.tsx
- src/routes/index.tsx
질문 게시판의 수정과 삭제 기능을 다른 게시판에도 연결.
---
---
- 알고리즘 문제 게시판을 제외한 모든 게시판에서 수정과 삭제가 가능합니다.
---
- 없음.
---
https://github.com/user-attachments/assets/cd3e2f20-d169-439d-89b0-d6d269031a29
---
- 불러올 때, 라우팅 문제가 있어, 기존의 개발직군문제 라우팅 경로를 수정했습니다.
> Zap: 모든 게시글 수정과 삭제 기능 추가

- src/components/list/AlgorithmListCard.tsx
- src/hooks/usePostLike.ts
- src/stores/problemStore.ts
- src/types/index.d.ts
- src/utils/fetchBjProblems.ts
---
---
- 알고리즘 문제 리스트에 좋아요 기능을 추가했습니다
---
---
- 알고리즘 문제 리시트 좋아요 추가
---
- 좋아요 기능과 관련한 usePostLike 훅을 만들어 사용했습니다.
> feat: 알고리즘 문제 리스트 좋아요 기능 추가

- src/pages/Signup.tsx
---
---
- 회원가입 시 중복 이메일인지 확인합니다
---
---
- 이미 가입한 이메일일 경우 
---
> feat: 회원가입 시 중복 이메일 확인

- src/components/atoms/Navigation.tsx
- src/components/list/ListCard.tsx
- src/components/list/ProfilePostCard.tsx
- src/layout/Header.tsx
- src/layout/MainLayout.tsx
- 프로필 게시글목록카드에 previewMarkdown 적용
- 헤더 높이, 폰트값, 로고크기 , 등 수정
- ListCard.tsx 높이값 일치 되도록 수정
---
---
> Design/UI : 헤더, ListCard css 수정

- src/components/detail/CommentItem.tsx
- src/components/ui/Avartar.tsx
댓글에 유저프로필사진 클릭시 해당 유저의 프로필페이지 이동
---
---
---
---
---
> feat: 댓글에 유저프로필 클릭시 유저프로필페이지 이동

- src/components/list/AlgorithmListCard.tsx
- src/components/list/AlgorithmListCardSkeleton.tsx
- src/pages/problem/algorithm/AlgorithmProblemList.tsx
---
---
- 알고리즘 문제 게시판에 스켈레톤을 추가했습니다.
---
---
- 스켈레톤
<br><br>
- 무한 스크롤 하단 스켈레톤
---
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
> feat: 알고리즘 문제 게시판 스켈레톤 추가

- src/pages/Login.tsx
- src/pages/Signup.tsx
---
---
- 회원가입 및 로그인 페이지에 메인으로 이동할 수 있는 로고를 추가했습니다.
---
---
- 로그인 페이지
<br><br>
- 회원가입 페이지
- 모바일
---
> feat: 회원가입 및 로그인 페이지 메인 이동 로고 추가

- src/pages/solution/algorithm/AlgorithmSolutionEdit.tsx
---
---
- 알고리즘 문제 풀이 취소 시 이전 페이지로 이동합니다
---
---
- 알고리즘 문제 풀이 버튼 기능 추가
---
> feat: 문제 풀이 시 취소 버튼 기능 추가

- src/components/list/ProfilePostCard.tsx
- src/components/main/MainRecommand.tsx
- src/components/main/MainUserInfo.tsx
- 프로필 페이지 게시글 구분텍스트 추가
- 메인 푼 문제 카운트 로직 변경
- 메인 추천문제 중복 방지
---
---
- 프로필 페이지 게시글 구분텍스트 추가
- 메인 푼 문제 카운트 로직 변경
- 메인 추천문제 중복 방지
> Feature/profile logic 

- src/components/main/MainNewProblem.tsx
- src/components/main/MainPopularProblem.tsx
- src/components/main/MainRecommand.tsx
- src/pages/HomePage.tsx
- 메인화면 비로그인 무한로딩 수정
- 메인화면 비로그인 문제 접근 제한
---
---
- 메인화면 비로그인 무한로딩 수정
- 메인화면 비로그인 문제 접근 제한
---
https://github.com/user-attachments/assets/62fae220-2565-4cf4-9a88-5318dab79a20
> Fix : 비로그인 화면 무한로딩, 비로그인 접근제한 수정

- src/components/detail/DetailText.tsx
- src/components/edit/EditText.tsx
- src/pages/question/QuestionEdit.tsx
- src/pages/solution/algorithm/AlgorithmSolutionEdit.tsx
---
---
- 글 작성 시 에디터 initial value를 제거했습니다.
- 알고리즘 문제 풀이 작성 시 제목 또는 내용 누락 시 alert가 발생하도록 했습니다.
- 알고리즘 문제 풀이 상세 페이지의 문제 내용 토글박스 화살표 버튼의 위치를 변경했습니다.
- 한글 태그 입력 오류를 해결했습니다.
- 태그 5개 초과 입력 시 alert가 발생합니다.
---
---
- 글 작성시 initial value 제거
<br><br>
- 알고리즘 문제 풀이 제목 또는 내용 누락시 alert 발생
<br><br>
- 알고리즘 문제 풀이 상세 페이지 토글박스 화살표 버튼 위치 변경
<br><br>
- 한글 태그 입력 오류 해결
<br><br>
- 태그 5개 초과 입력시 alert 발생
---
> fix: 알고리즘 문제 풀이 페이지 및 알고리즘 풀이 상세 페이지 오류 해결

- src/components/detail/CommentEdit.tsx
> fix: 에러 해결

- src/components/search/AlgorithmTag.tsx
- src/components/search/SearchTag.tsx
- src/components/ui/Avartar.tsx
- src/data/tagDummyData.ts
- src/pages/NotFound.tsx
- src/pages/problem/algorithm/AlgorithmProblemList.tsx
- src/stores/problemStore.ts
- src/utils/fetchBjProblems.ts
개발직군 문제도 자동완성 태그 검색 기능이 추가되었습니다
---
---
- 이제 개발직군 문제도 자동완성 태그 검색이 가능합니다
- 자동완성을 위한 알고리즘 분류 데이터는 src/data/tagDummyData.ts에 추가되어 있습니다
따라서, 이후에 별도로 알고리즘 분류를 추가하는 작업이 필요합니다
- 이외에 404페이지 수정이 있습니다.
---
- 없음.
---
https://github.com/user-attachments/assets/9e5d0c5d-079c-4b7c-b76f-684830af8584
태그 자동완성
404 페이지 수정
---
- 없음.
> Feat: 개발직군 문제 태그 자동완성 검색

- src/components/list/ListCard.tsx
- src/components/main/MainUserInfo.tsx
- src/layout/Header.tsx
- src/layout/Sidebar.tsx
- src/pages/HomePage.tsx
- src/styles/index.css
- 메인 메뉴  CSS 누락 수정
- listCard.tsx CSS 누락 수정
- Header 사용자 데이터 가져오는 로직 변경 - 프로필 이미지 변경시 이미지 변경이 안됐었음
- Sidebar 사용자 데이터 가져오는 로직 변경 - 프로필 이미지 변경시 이미지 변경이 안됐었음
---
---
- 메인 메뉴  CSS 누락 수정
- listCard.tsx CSS 누락 수정
- Header 사용자 데이터 가져오는 로직 변경 - 프로필 이미지 변경시 이미지 변경이 안됐었음
- Sidebar 사용자 데이터 가져오는 로직 변경 - 프로필 이미지 변경시 이미지 변경이 안됐었음
---
- 메인
- listCard.tsx
- 프로필이미지 변경시 Header, SideBar 변경 적용
https://github.com/user-attachments/assets/d6e7a960-523a-4396-986a-dde07d556424
> Feature/main UI

- src/api/mainApi.ts
- src/components/edit/EditText.types.ts
- src/components/list/AlgorithmListCard.tsx
- src/components/main/MainPopularProblem.tsx
- src/components/main/MainRecommand.tsx
- src/loader/post.loader.ts
- src/pages/solution/algorithm/AlgorithmSolutionEdit.tsx
> fix: 라우팅 오류 해결

- src/loader/profile.loader.ts
- 프로필 페이지 좋아요 탭에서 삭제된 게시글도 보여서 안보이게 수정했습니다.
---
---
- 프로필 페이지 좋아요 탭에서 삭제된 게시글도 보여서 안보이게 수정했습니다.
> Fix : 좋아요 된 삭제게시글도 보여서 수정

- src/utils/customAlert.ts
> design: 모바일의 경우 상단 중앙, 이 외 상단 우측에 위치
